---
- name: Create group for Google Auth users
  group:
    name: "{{ google_mfa_config_usergroup }}"
    state: present


- name: Configure OpenSSH for Google Auth
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
    insertafter: '{{ item.insertafter | default(omit) }}'
    state: present
  with_items:
    - regexp: '^ChallengeResponseAuthentication.*'
      line: 'ChallengeResponseAuthentication yes'
    - regexp: '^Match Group {{ google_mfa_config_usergroup }}'
      line: 'Match Group {{ google_mfa_config_usergroup }}'
      insertafter: EOF
    - regexp: '^\s+AuthenticationMethods \"publickey,keyboard-interactive:pam\"'
      line: '    AuthenticationMethods "publickey,keyboard-interactive:pam"'
      insertafter: '^Match Group {{ google_mfa_config_usergroup }}'
  notify: restart ssh


- name: Configure SSH PAM for Google Auth
  lineinfile:
    dest: /etc/pam.d/sshd
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
    insertafter: '{{ item.insertafter | default(omit) }}'
    state: present
  with_items:
    - regexp: '^#?\@include common-auth'
      line: '#@include common-auth'
    - regexp: '^auth required pam_google_authenticator.so'
      line: 'auth required pam_google_authenticator.so'
      insertafter: '#@include common-auth'

